### ISSUE TITLE
Authentication requires something after the user identity in partial realms

### ISSUE THREAD

**Issue by programaths** [realm/realm-graphql-service#81] opened 2018-11-27 08:36 UTC
### Issue description
When we authenticate a token on a given path, the server do user identity check by comparing the token user id with the user id contained in the partial realm path.

The check expect the path to end with a "/"  . (`/*`)

That means that one has to add a "/" and something after as the ROS do not allow paths terminating with "/" for authentication.

```
path is invalid. It should start with a slash, consist of Latin letters (A-Z, a-z), digits (0-9), dot (.), dash (-), and underscore (_). All components should be non-empty and not start with a dot. The path should not end with .realm, .realm.lock or .realm.management
```

### Test ? Code ? Step to reproduce ?

See code here: https://gist.github.com/programaths/a1de2e794a0be9a1010eb32eb7d8857a

Remove "ok" where it is commented so: it should fails.

### Possible solution

Do not enfore path ending with "/" to allow authenticating said path.

PR to follow

### System info

Version: 3.4.0
Os (uname -a) : Linux b50dc1da542b 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 GNU/Linux
Node version: v10.11.0

**Comment by nirinchev** [comment] 2018-11-27 09:34
This is by design, the convention we have for query based Realm paths is `/reference-realm/__partial/user-id/some-hash` where `some-hash` is generally an id that's unique for the device. This allows the same user to have different partial views of the reference Realm on different devices. Of course, you can hardcode a hash value and then you'll only have a single Realm per user. Is there a particular reason you want to avoid having the hash at the end of the url?

**Comment by nirinchev** [comment] 2018-11-27 11:20
I'm not sure I fully understand the use case, sorry. Why would it matter for your web app if you have some random hash after the user id or not?

**Comment by nirinchev** [comment] 2018-11-27 12:38
I understand. I'm not entirely sure this is a supported scenario at the moment though. I believe some components rely on the template I showed (i.e. having a segment after the user-id segment). I can do some tests and verify if that will work, but my recommendation would be to just hardcode some hash in your web app - for example, in the reference implementation of a GraphQL client, we use `graphql-client` for all consumers of the client, you could just do `user-id/my-web-app`.

**Comment by nirinchev** [comment] 2018-12-10 10:43
Closing this as there is a workaround that doesn't involve redesigning our other components.

**Closed by nirinchev** 2018-12-10 10:43 UTC
Labels: O:User, T:Enhancement
