### ISSUE TITLE
As a user I would like to query against a Realm in query-based mode

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-graphql-service#70] opened 2018-08-20 10:51 UTC
The [My First Realm App](https://github.com/realm/my-first-realm-app) uses the new default configurations to open a Realm in query-based mode, for users to create an Android, iOS and Web app that syncs against the same database the user needs a way to open a Realm in query-based mode via the Graph QL service.

It would also be desirable to be able to create and remove subscriptions from the query-based Realm. A future enhancement could be to have subscriptions being created automagically when the user makes Graph QL queries.

**Comment by kraenhansen** [comment] 2018-08-21 11:26
It turns out that opening a query-based (partial) realm actually crashes ROS with:

```
fatal: Detected an unhandled promise rejection at: [object Promise] reason: Error: A Realm URL may not contain the reserved string "/__partial/".
    at Promise (/app/node_modules/realm/lib/extensions.js:85:29)
    at new Promise (&lt;anonymous&gt;)
    at Function.open (/app/node_modules/realm/lib/extensions.js:84:27)
    at RealmFactory.&lt;anonymous&gt; (/app/node_modules/realm-object-server/dist/RealmFactory.js:111:41)
    at Generator.next (&lt;anonymous&gt;)
    at fulfilled (/app/node_modules/realm-object-server/dist/RealmFactory.js:4:58)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)
fatal: Exiting code 1
```

**Comment by nirinchev** [comment] 2018-10-16 11:13
Duplicate of https://github.com/realm/realm-object-server-private/issues/1289

**Closed by nirinchev** 2018-10-16 11:13 UTC
Labels: T:Bug-Crash
