### ISSUE TITLE
Realm Sync Observation

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-graphql-service#50] opened 2018-06-07 01:20 UTC
I have an observation, when i sync to a specific class, while adding data to that class continuously, its syncing is slow. Is this normal?

**Comment by nirinchev** [comment] 2018-06-07 02:48
I'm not sure what you mean by "syncing is slow". Can you share more details, ideally a project that reproduces the problem?

**Comment by nirinchev** [comment] 2018-06-11 11:16
@howdyhyber pinging you for more info on this issue, otherwise I'll close it since there's nothing we can do.

**Comment by howdyhyber** [comment] 2018-06-12 02:02
@nirinchev just close this issue for , ill try to replicate in on our end so i can gie you more input.

**Comment by nirinchev** [comment] 2018-06-12 07:48
Thanks :) If you replicate it, feel free to reopen and post the instructions and we'll take a look.

**Closed by nirinchev** 2018-06-12 07:48 UTC
Labels: O:User
