### ISSUE TITLE
GraphQL Schema is not updated after it has been queried

### ISSUE THREAD

**Issue by mgeerling** [realm/realm-graphql-service#37] opened 2018-03-06 20:03 UTC
Reported here https://forums.realm.io/t/update-to-graphql-schema/1034

To repro:
1) query graphQL endpoint 
2) Updated a class' schema (via studio or other methods) 
3) query endpoint again

**Comment by nirinchev** [comment] 2018-03-06 20:45
This is not a bug. By design the graphql service caches the schema of realms because it has to be computed for each request and is far more expensive than the request itself. The GraphQL service exposes configuration options to control the maximum number of schemas in the cache as well as the max age of these schemas. If they are self hosting, they can configure it when creating the service. If they are using cloud, they are out of luck, because cloud defaults to infinite max age, so they either have to create a thousand realms and query each of them to evict the original realm's schema from the cache (cloud defaults to 1000 schemas max in the cache) or wait until https://github.com/realm/raas/issues/602 is resolved.

I'm going to close this as it's not a bug with the GraphQL service.

**Comment by nirinchev** [comment] 2018-03-06 21:31
Actually, I decided it makes sense to expose an endpoint for invalidating a cached schema entry. This should solve this user's issue.

**Closed** 2018-03-06 22:04 UTC
Labels: O:User, T:Bug

**Comment by astigsen** [comment] 2018-03-08 10:44
Could we version the schemas in the cache so that we can update them when there is a newer version in the realm?

**Comment by kneth** [comment] 2018-03-08 13:34
Only https://realm.io/docs/javascript/latest/api/Realm.html#schemaVersion

**Comment by nirinchev** [comment] 2018-03-08 13:43
Hm... does the schema version for synchronized Realms increase automatically when the client integrates changes?

**Comment by kneth** [comment] 2018-03-09 07:49
No, and I don't think schema version is used for anything when you are in additive mode.

@tgoyne Can you enlighten us?

**Comment by tgoyne** [comment] 2018-03-09 16:01
The object store invokes a callback (BindingContext::schema_did_change()) whenever the schema for a Realm changes, which JS currently does not implement. I don't think any bindings currently expose this (Java uses it internally and Cocoa *should* use it internally but with the Browser being deprecated it's never been a pressing task), so there's no precedent for what the public API should look like.

**Comment by kneth** [comment] 2018-03-12 09:29
@nirinchev If you think a callback could help, please create a Realm JS issue for it.
